### ISSUE TITLE
Try...Catch doesn't interrupt goto()

### ISSUE THREAD

**Issue by DeForce** [colobot/colobot#474]
Good day,

I have code that interrupts goto() if bot is low on energy, and then goes to recharge himself and go back, but seems like goto() doesn't flush the location he has to go to.
When debugging goto() starts to execute, but it goes to the location of the thing he needed to go, not powerstation. Did I miss something in my code?

Code: http://pastebin.com/98nkRgrh

Best Regards,
DeForce

**Comment by tomaszkax86** [comment]
I believe try...catch doesn't flush currently executing task. This makes some weird errors in next instructions. Code below causes wait(2) not to work and move(-2) doesn't move backwards.

```
extern void object::Test()
{
    object item = radar(TitaniumOre);

    turn(direction(item.position));

    float dist = distance(position, item.position);

    try
    {
        move(dist);
    }
    catch(distance(position, item.position) < 5)
    {
        message("Stop");
    }

    wait(2);
    move(-2);
}
```

try...catch seems unstable. We'll have to look into it.

**Comment by melex750** [comment]
The complete syntax for the  try.....catch block.
seems to work ok.

```java
    int err = 0; // must be of type int
    try
    {            //works for all functions() that return int

        err = move(4);  // path is blocked

        throw err;         //<----prog. exits if err < 0
    }
    catch ( err )          //<---only works with errmode(0);
    {
        move(-10);         //<--  executes if err > 0  
    }
    finally      
    {
        turn(90);          //<--  executes in any case
    }

    // program continues normally
```

**Comment by krzys-h** [comment]
This works correctly because execution of move() has finished already when you throw an error. The version that takes a condition in catch instead of thrown value is broken, because the condition may break long-running instructions.

**Comment by krzys-h** [comment]
Wait a moment, does it actually work like that? I could never get it to catch into a variable like that.

**Comment by melex750** [comment]
I took some time but this is what I found in CbotWhile.cpp
If throw receives a negative, program the program stops with
"Negative value rejected by throw" message.
It could be fixed with  `!=` instead of  `value > 0`.

**Comment by melex750** [comment]
I am fairly certain I found the bug with catch.
on line 1176 you have this in the test catch function called from line 1005.
i believe it should be  `== CBotTypBoolean` and i think it need an `else return false;'
```c++

    if ( val > 0 || pile->GetType() != CBotTypBoolean )
    {
        CBotVar* var = CBotVar::Create(static_cast<CBotToken*>(nullptr), CBotTypBoolean);
        var->SetValInt( pile->GetVal() == val );
        pile->SetVar(var);                          // calls on the stack
    }

return true;
```
Why create a boolean if it is not a boolean? :(

**Comment by krzys-h** [comment]
The booleans worked last time I checked, it's just that the long-running tasks weren't stopped properly, and that's implemented on Colobot side (not the CBot library), see CScript::m_bContinue or something like that.
This has a side effect of allowing instructions like goto() to run in the background while executing some other code, but that's not how it was supposed to work.

**Comment by melex750** [comment]
I think I get it now. I was testing try....catch at a short distance, and it worked well with goto and move.
But it seems that `catch` waits for an error,  and if goto and move would detect and obstacle and return a "one" before crashing, then `try..catch` might be more useful.
Right now it acts like a fancy  "`if`"  statement. It does work though. with boolean and integer.

With testing it appears that the parameter for `catch` is evaluated before running the commands
after `try`, so it would seem that using a variable for catch is best. `throw` only accepts the type of `int`.

**Comment by CyborgMaster** [comment]
I was looking into this briefly due to my struggles with #818.  It seems tricky.  Right now I don't know if any CBot classes have hooks into the CTaskExecutorObject.  If I can get ahold of that, then we can tell it to stop the foreground tack when a catch condition fires.  Anyone know how I might find the current CTaskExecutorObject or the current CScript object (which has a reference to CTaskExecutorObject)?

**Comment by melex750** [comment]
@CyborgMaster This is what I did to solve it.
[patches.zip](https://www.dropbox.com/s/e08axzmjcgpt49p/patches.zip?dl=1)
```
try {...}
catch(true)
{
    abort();
    motor(0,0);
}
```

**Comment by CyborgMaster** [comment]
@melex750, brilliant!  I love it.  It makes a lot of sense as well.  CBot doesn't have the concept of long running background or foreground tasks.  That's layered on top of it by the game engine, so of course CBot can't directly stop a foreground task.  Therefore, the only way to handle it is to add an extra command on the engine side to do it.  

I'm going to start using your patch now, but put a pull request up ASAP and lets get this merged into the game so other people can start using it!

**Comment by melex750** [comment]
@CyborgMaster  ```catch()``` also catches runtime errors.
Some defined constants **[listed here](https://github.com/colobot/colobot/blob/master/src/CBot/CBotProgram.cpp#L387-L398)**.

**Comment by CyborgMaster** [comment]
Right.  I would actually love to be able to throw an integer and catch it further up the stack, like you would be able to in a normal language.  It seems, base on my experiments, that the throws only are caught if they are directly inside the try block, not inside a function called from the try block.  But that's a different issue.  Let's first get your patch merged and then we can tackle other try/catch improvements.

**Comment by krzys-h** [comment]
abort(); makes no sense to me at the moment, it looks like a veey hacky workaround. It would be a whole different story if we added a way to start tasks asynchronously and check if a task is currently running. Also, not all tasks can be aborted (e.g. grab/drop), this needs to be handled somehow.

@CyborgMaster Please make a new issue for try/catch not propagating on the stack I'll probably forget about it when closing this issue if you just leave it in a comment

**Comment by CyborgMaster** [comment]
@krzys-h I was working on opening a new issue for throwing up the stack, but I couldn't even get a simple sample to work.  

```c++
extern void object::Test() {
	int error = 0;
	int caught = 0;
	try {
		error = 1;
		throw error;
	} catch(caught) {
		message("Caught error: " + caught);
	}
}
```

This just dies with "Internal Error - tell the developers" (which is because I'm throwing a 1).  I can't get catching a value to work at all.  Is there something I'm missing?

**Comment by CyborgMaster** [comment]
@krzys-h I agree that `abort` is a little hacky, but I can't see a reasonable way to do it any other way.  CBot the language doesn't have the concept of long running commands like `goto`.  I can't see how it would know it should try and stop a `goto` if the catch test passed, because it doesn't know that `x = goto(pos)` is any different then `x = abs(-10)`.  Maybe when we get around to rewriting CBot, we can bake in the difference between "instant" commands, and "long-running" commands that catch should stop, but I'm not that could be done with the engine in its current state.  

I vote we accept the `abort` patch for now.  That way people can start using `catch(condition)` for what it was intended, and then we can make it more intuitive when we rewrite the engine.  Without something like this, there is no way for me to stop the robot when it gets stuck like in #818, or if it gets too close to an alien.  

As far as grab/drop, we should improve the `abort` command to know the difference between tasks it can and can't interrupt.

**Comment by CyborgMaster** [comment]
Side note: I've been programming with `abort` for a couple days now and it works beautifully, allowing me to get around #818, and a couple other corner cases that are impossible without it.

**Comment by melex750** [comment]
@CyborgMaster , The catch parameter is the value that you are trying to catch,
so in your example setting ```caught = 1;``` is the way to make it work.
I find it to work even with this example:
```c++
void test1(){throw 100;}
void test2(){test1();}
extern void object::New()
{
	try {test1();}
	catch(100) message("catch 100");
	message("test1 passed");
	
	try {test2();}
	catch(100) message("catch 100");
	message("test2 passed");
}
```
That's not to say it works in all cases. There may be problems when
calling public functions from a different program, for example. 

I do know, that it may not unlock a class, if a synchronized method was executing
when catch condition is found true, I think there's an easy fix for that tho.

------------------------------------
It is definitely a very hacky patch. I had a much better idea moments after I shared it,
one that will only work on goto and move. I'll be trying the new idea tomorrow. ```abort 2.0``` ;)

**Comment by CyborgMaster** [comment]
@melex750.  Awesome!  I understand now.  I'm glad there is someone like you on this issue tracker who understands all this stuff.  We really should get this into the SatCom documentation. 

So if I understand it correctly, in most languages you put a variable into the catch parens and it is resolved with whatever is thrown.  ex:

``` cpp
try {
  throw new DatabaseException("bad column name");
} catch(Exception e) {
  // Here `e` is the instance of DatabaseException created above
}
```

However, in CBot, instead of catching exception types, you instead throw and catch integers.  And because the integers represent the exception types (there are no exception instances), they are constants and so you don't need an exception variable.  So you just throw and catch integer constants.  Luckily if you have multiple exception modes you can have multiple catch blocks that handle the different exception types (integers), like so: 

This will print either "Caught 2" or "Caught 3" based off the random test inside the function.

``` cpp
void test1() {
	if (rand() > 0.5) {
		throw 2;
	} else { 
		throw 3;
	}
}

extern void Main() {
	try {
		test1();
	} catch(2) {
		message("Caught 2");
	} catch(3) {
		message("Caught 3");
	}
}
```

It seems like the `goto`, `grab`, etc use the same throw semantics as described here.  Maybe if we document it properly we should eliminate `errmode(0)` and just let people catch their exceptions.  It seems like on `errmode(1)` it throws the integer constant and on `errmode(0)` it returns it.  It might be beneficial from an educational perspective to for a try/catch and take that opportunity to teach people how those work.  Trying to goto an "inaccessible destination" is definitely an exceptional occurrence.  This is simply an integer constant defined in `error.h` as 
```cpp
ERR_GOTO_IMPOSSIBLE   = 210,      //! <  goto impossible
```
with the error message defined in `restext.cpp` as 
```cpp
stringsErr[ERR_GOTO_IMPOSSIBLE] = TR("Goto: inaccessible destination");
```

You can even write `throw 210;` and get "Goto: inaccessible destination" to print out.  So if we just made these integer constants recognized like we do categories then people could write code like this:

```cpp
try {
  goto(pos);
} catch(GotoInaccessible) {
  // try something else (like a winged bot)
}
```
------

I'm very excited to see `abort 2.0`.  It will be interesting to see what you come up with.  I'm a bit at a loss as to how it could be done better.

**Comment by melex750** [comment]
@CyborgMaster , ```errmode(0);``` just prevents halting the program and instead returns the error, which
can be a convenient way to handle an exception(ex. grab/drop). You can do the same thing with try/catch plus define more complex error handling. I think both are very useful.

The catch parameters are repeatedly evaluated during execution of the try block, so it could even be used to monitor the value of a variable```catch(i == 3)```, not sure how useful that is though.

**Comment by Kubus11** [comment]
So, anything new in this case?

**Comment by frikadelki** [comment]
It's a real shame this still does not work. Solution with abort looks acceptable if it does the job of interrupting goto. @CyborgMaster, @melex750, @krzys-h any chance this is going to happen in some form?

// Some off-topic/rant
I'm a software developer in real life. So, after returning to the game after 12 or so years, and not remembering much, I've just wanted to program bots to the best of my ability, you know. All my excitement went 'poof' after about 30 minutes of gameplay, once i've gained flying ability and tried to program bots to do some basic routine stuff. Like gathering and recharging dead batteries or gathering titanium/cubes. 
Immediately I discovered that goto is totally broken. So, over the course of 3 days:
- I've tried a bunch of different versions of the game, including the original 1.8e
- I've learned to always use goto(space(target, ...)); before actually goto(target)
- I've learned to dead-zone spaceship-surrounding area
- And now I've learned that the last resort that I thought I had (the try/catch around goto with detectstuck-dash-tryagain) is also not an option
Apparently I must write my own goto after all. Which looks like a pain considering CBot limited map access and all the other quirks (and I'm not really sure it's possible at all). More so it looks like a standard day-job-type task, and not having fun while programming bots.
So, really, what was the point of naming this "Colobot Gold" and doing all this other improvements, if the basic bot's movement command is still in the same sad state?

Also, please, write in big red letters "THIS DOES NOT WORK, DO NOT USE IT" on this page https://colobot.info/did_you_know/theres-a-mysterious-try-catch-block-statement-in-cbot-that-allows-you-to-interrupt-normally-non-interruptible-instructions-like-move-and-goto/
at the moment it looks very much like an invitation to use it. Or better yet make it a compile-time error.

Sorry about coming down so hard. I realise you do this as a hobby. Just, you know, decided to share the experience and emotions.

**Comment by MrSimbax** [comment]
> So, really, what was the point of naming this "Colobot Gold" and doing all this other improvements, if the basic bot's movement command is still in the same sad state?

Nobody is more sad than us that it has not improved more but the game has improved a lot nevertheless. I can definitely feel your pain about movement commands, as probably most people who tried to write anything more complicated in CBOT.

> Also, please, write in big red letters "THIS DOES NOT WORK, DO NOT USE IT" on this page 

I thought until now that the word "mysterious" and the section being called "did you know" were enough of a hint that this is experimental stuff which may work in unexpected ways or not work at all but point taken. I think we should remove the sidebar completely as there's nothing useful to put there right now.

Anyway, try..catch block is not (?) a documented feature so for anybody reading this, it is not recommended to use it as it might not work or work in unexpected ways.

>Immediately I discovered that goto is totally broken

With CBOT you have currently really only two options:
1. Accept that programs will be unreliable even on normal simulation speed and be ready to restart your programs or even whole levels.
2. Accept that programs will be unreliable ;) but a little more than usually and wrap the movement operations in your own functions and use `errmode(0)` with hacky algorithms like "retry goto until you get there within epsilon distance". It's basically a must for base building programs or code battles and this is what I've seen people do and what I do myself. Here's a not tested example:
```
void trygoto(point pos)
{
    errmode(0);
    while (goto(pos) != 0) wait(1);
    errmode(1);
}
```
You might want to tweak it a little bit depending on your specific scenario and experience, for example try to change a position a little bit with other movement commands or `goto(space())`, maybe give up after a fixed number of tries etc. Yeah, it's not fun and it's sad that you have to do it in the first place but it's much less work than writing your own goto and usually it gets the job done. I don't believe anyone managed to come close to writing their own goto, and I am pretty sure smarter people than me tried. Rewriting it in the engine isn't exactly a trivial task either to put it mildly otherwise I'd assume someone would already have done it.

Also, in the most basic scenarios `goto()` shouldn't be *that* broken unless you increase the simulation speed as then all hell breaks loose as even the simple movement instructions start to break and `move(3)` starts to mean different things depending on the mood of your game. Fortunately, there were significant improvements at least in that matter in https://github.com/colobot/colobot/pull/1257

**Comment by SimonHeimberg** [comment]
> @CyborgMaster This is what I did to solve it.
> patches.zip
> 
> ```
> try {...}
> catch(true)
> {
>     abort();
>     motor(0,0);
> }
> ```

I support the idea of a new command like abort(), or maybe abort_movement(). I see no better way currently. And it would be handy to interrupt goto() and charge the PowerCell or flee when under attack.
Unfortunately the zip file is not available anymore. And no PR was created. Does anybody have it?

**Comment by X64E** [comment]
Maybe stop all actions when catch==true? Without abort.

**Comment by xpopov** [comment]
Hmm, today I've spent 20 minutes to find out how to implement stopping command. So goto is a foreground task, and you just need to register and implement command in **scriptfunc.cpp**:
`script->m_taskExecutor->StopForegroundTask();`

That allows to interrupt goto commands, e.g. when enemy is too close to the bot, and we need to escape or fight

**Comment by hexagonrecursion** [comment]
* Progress report: I can't continue laying the groundwork for implementing this until someone merges https://github.com/colobot/colobot/pull/1627 or requests changes in that pull request

**Comment by hexagonrecursion** [comment]
Thanks, @tomaszkax86 for merging #1627. The next self-contained pull request that lays the groundwork for this feature is **ready for review**: #1664

**Comment by hexagonrecursion** [comment]
* @tomaszkax86 #1664 is ready for review now.

**Comment by hexagonrecursion** [comment]
* https://github.com/colobot/colobot/pull/1684 is ready for review now.
